### ISSUE TITLE
他の同様なプロジェクトで利用している用語の利用

### ISSUE THREAD

**Issue by kenue** [muramurasan/okuribito#22]
検索しやすいように他のプロジェクトで使わている単語を用いたほうが良いと思います。
obsoleteやdeprecateという文字が入っていれば検索されやすいです。

**Comment by muramurasan** [comment]
issue建設ありがとうございます！
これはgem名の話でしょうか？ readmeの話でしょうか？

**Comment by muramurasan** [comment]
以下の文言を冒頭に入れてみました！
```
... In other words, it can be used in order to extract the obsolete method.
```
