### ISSUE TITLE
rails g model xxxをするとき、okuribito.ymlに記載されているすべてのクラスがない場合エラーが発生する

### ISSUE THREAD

**Issue by satoke** [muramurasan/okuribito#23]
タイトル通り、rails g model xxxをするとき、okuribito.ymlに記載されているすべてのクラスがない場合エラーが発生します。

ほげほげ

**Comment by muramurasan** [comment]
okuribitoをインストールしているプロジェクトで、`rails g model xxx` をするとエラーになるってことですよね？
後回しになりすぎないように対応します......

**Comment by muramurasan** [comment]
再現できず。.... orz

**Comment by muramurasan** [comment]
We could'nt catch the this error for a long time, so close this issue.
